stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - src/utils.py
    outs:
      - data/raw
    

  
  feature_engineering:
    cmd: python src/components/feature_engineering.py
    deps:
    - src/components/feature_engineering.py
    - src/utils.py
    - data/raw/raw.csv
    
    outs:
    - data/process

  # feature_engineering:
  #   cmd: python src/componenmts/feature_engineering.py
  #   deps:
  #     - src/components/feature_engineering.py
  #     - Data/Raw/raw.csv
  #   outs:
  #     - Data/Process/clean.csv
  #     - Data/Process/train.csv
  #     - Data/Process/test.csv
        


  data_transformation:
    cmd: python src/components/data_transformation.py
    deps:
    - src/components/data_transformation.py
    - src/utils.py
    - data/process/train.csv
    - data/process/test.csv
    
    outs:
    - data/transformation
        


  model_training:
    cmd: python src/components/model_training.py

    deps:
    - src/components/model_training.py
    - src/utils.py
    - data/transformation/processor.pkl
    - data/transformation/train_array.npy
    - data/transformation/test_array.npy

    outs:
    - models