stages:
  prepare_data:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - src/utils.py
    outs:
      - Data/Raw
    

  
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - src/utils.py
    - Data/Raw/raw.csv
    
    outs:
    - Data/Process
        


  data_transformation:
    cmd: python src/data_transformation.py
    deps:
    - src/data_transformation.py
    - src/utils.py
    - Data/Process/train.csv
    - Data/Process/test.csv
    
    outs:
    - Data_transformation
        


  model_training:
    cmd: python src/model_training.py
    
    deps:
    - src/model_training.py
    - src/utils.py
    - Data_transformation/processor.pkl
    - Data_transformation/train_array.npy
    - Data_transformation/test_array.npy

    outs:
    - Models